import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { contractAddress } from "../constants/address";
import { abi } from "../constants/abi";

import { useConnectWallet } from "@web3-onboard/react";
import { ethers } from "ethers";

const buttonStyles = {
  borderRadius: "6px",
  background: "#111827",
  border: "none",
  fontSize: "18px",
  fontWeight: "600",
  cursor: "pointer",
  color: "white",
  padding: "14px 12px",
  marginTop: "40px",
  fontFamily: "inherit",
};

export default function Home() {
  const [{ wallet, connecting }, connect, disconnect] = useConnectWallet();

  const [txHash, setTxHash] = useState("");

  // create an ethers provider
  // @ts-ignore
  let ethersProvider;

  if (wallet) {
    ethersProvider = new ethers.providers.Web3Provider(wallet.provider, "any");
  }

  async function mintNFT() {
    console.log("====== Minting Wave Form NFT ======");


    // @ts-ignore
    if (!ethersProvider) {
      console.log("provider not initialized yet");
      return;
    }
    const signer = await ethersProvider.getSigner();
    console.log(signer);
    
    const contract = new ethers.Contract(contractAddress, abi, signer);

    // Prepare the transaction
    const unsignedTx = await contract.populateTransaction.mint();

    // Sign the transaction (not as a fee payer)
    const signedTx = await signer.signTransaction(unsignedTx);

    // Send the signed transaction to our fee delegation server
    const response = await fetch('http://localhost:3001/fee-delegation', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ rawTransaction: signedTx }),
    });

    if (!response.ok) {
      throw new Error('Fee delegation failed');
    }

    const result = await response.json();
    console.log('Transaction sent:', result.transactionHash);
    setTxHash(result.transactionHash);
    // console.log(receipt);
    // console.log(receipt.transactionHash);
    // setTxHash(receipt.transactionHash);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {!wallet?.accounts ? (
          <button
            style={buttonStyles}
            disabled={connecting}
            onClick={() => (wallet ? disconnect(wallet) : connect())}
          >
            {connecting ? "Connecting" : wallet ? "Disconnect" : "Connect"}
          </button>
        ) : (
          <div className={styles.title}>
            <h1 className={styles.title}>
              Demo of Kaia{" "}
              <a
                className={styles.kaialink}
                href="https://docs.kaia.io/learn/transactions/fee-delegation/"
              >
                {" "}
                Gas Abstraction
              </a>
            </h1>
            <button onClick={mintNFT} className={styles.mintBtn}>
              Mint WaveForm NFT
            </button>

            {txHash && (
              <a
                className={styles.viewExplorer}
                href={`https://kairos.kaiascan.io/tx/${txHash}`}
                target="blank"
              >
                View on Explorer
              </a>
            )}
          </div>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://docs.kaia.io/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/kaia.svg" alt="Vercel Logo" width={52} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
